name: Build and run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Boost
        run: |
          sudo apt update
          sudo apt install -y libboost-all-dev

      - uses: actions/checkout@v3

      - name: Build and run tests
        run: ./health_check.sh
